
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";
/* import TopNav from "@/components/navBar/topNav/TopNav"; */
import { CartProvider } from "@/components/context/CartContext";
import { AuthProvider } from '@/components/context/AuthContext'


export const metadata = {
  title: "HOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <NavBar />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
