
import "./globals.css";
import NavBar from "@/components/navBar/NavBar";
/* import TopNav from "@/components/navBar/topNav/TopNav"; */
import { CartProvider } from "@/components/context/CartContext";



export const metadata = {
  title: "HOME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <CartProvider>
        <NavBar />
        {children}
        </CartProvider>
      </body>
    </html>
  );
}
